return {
  "nvim-treesitter/nvim-treesitter",
  opts = {
    ensure_installed = {
      "c",
      "c_sharp",
      "javascript",
      "typescript",
      "css",
      "gitignore",
      "dockerfile",
      "graphql",
      "http",
      "json",
      "scss",
      "query",
      "sql",
      "vim",
      "vimdoc",
      "lua",
      "markdown",
      "markdown_inline",
    },
  },
}
